/**
 * Service-worker lifecycle + install prompt (plan §2.8). Registers the Workbox
 * SW generated by vite-plugin-pwa and bridges its events into the store so a
 * lightweight banner can offer "reload to update" / "install app". The SW only
 * exists in production builds (devOptions disabled), so this is a no-op in dev.
 */
import { registerSW } from 'virtual:pwa-register'
import { useAppStore } from '@/store/appStore'

/** `beforeinstallprompt` isn't in the standard lib DOM types. */
interface BeforeInstallPromptEvent extends Event {
  prompt: () => Promise<void>
}

let updateSW: ((reloadPage?: boolean) => Promise<void>) | null = null
let deferredInstall: BeforeInstallPromptEvent | null = null

export function initPWA(): void {
  updateSW = registerSW({
    onNeedRefresh() {
      useAppStore.getState().patchPwa({ needRefresh: true })
    },
    onOfflineReady() {
      useAppStore.getState().patchPwa({ offlineReady: true })
    },
  })

  window.addEventListener('beforeinstallprompt', (e) => {
    e.preventDefault()
    deferredInstall = e as BeforeInstallPromptEvent
    useAppStore.getState().patchPwa({ canInstall: true })
  })
  window.addEventListener('appinstalled', () => {
    deferredInstall = null
    useAppStore.getState().patchPwa({ canInstall: false })
  })
}

/** Activate the waiting SW and reload onto the new version. */
export function reloadForUpdate(): void {
  useAppStore.getState().patchPwa({ needRefresh: false })
  void updateSW?.(true)
}

/** Dismiss the banner (update / offline-ready / install) without acting. */
export function dismissPwaBanner(): void {
  useAppStore.getState().patchPwa({ needRefresh: false, offlineReady: false, canInstall: false })
}

/** Show the browser's native install prompt (Chromium). */
export async function promptInstall(): Promise<void> {
  if (!deferredInstall) return
  await deferredInstall.prompt()
  deferredInstall = null
  useAppStore.getState().patchPwa({ canInstall: false })
}
